name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.1.2
        id: coverage
        with:
          test-script: yarn test
          output: report-markdown

      - name: Comments
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
